import type { AppConfig } from './types'

export const appConfig: AppConfig = {
  appId: 'test-1',
  name: '',
  platform: 'mobile',
  description: '描述信息',
  dependence: '',
  services: [],
  layout: { width: '100%', center: true },
  themeConfig: {
    CssVars: {
      '--app-c-bg': '#fff',
      '--app-c-text': '#000',
      '--app-c-brand': '',
    },
  },
  pages: [
    {
      title: '首页',
      path: '/',
      isHome: true,
      config: {},
      blocks: [
        {
          type: 'block',
          label: 'vant-cell_0',
          widget: { id: 'vant-cell', version: '1.0.0', js: '', css: '' },
          bid: 'com_yxyrezklkf',
          props: {
            'title': '标题',
            'value': '副标题',
            'label': '描述信息',
            'size': 'normal',
            'url': '',
            'clickable': false,
            'is-link': false,
            'arrow-direction': 'right',
            'center': false,
          },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
        {
          type: 'block',
          label: 'vant-button_0',
          widget: { id: 'vant-button', version: '1.0.0', js: '', css: '' },
          bid: 'com_rfsracndzg',
          props: {
            text: '按钮',
            type: 'default',
            size: 'normal',
            icon: '',
            block: false,
            plain: false,
            square: false,
            round: false,
            disabled: false,
            hairline: false,
            url: '',
          },
          styles: {
            display: 'inline-block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
        {
          type: 'block',
          label: '栅格布局_0',
          widget: { id: 'gird-container', version: '1.0.0', js: '', css: '' },
          bid: 'com_ykbkbkkfqy',
          props: { cols: [12, 12] },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {
            'col-0': [
              {
                type: 'block',
                label: 'vant-button_1',
                widget: {
                  id: 'vant-button',
                  version: '1.0.0',
                  js: '',
                  css: '',
                },
                bid: 'com_ydwhyyxbsm',
                props: {
                  text: '按钮',
                  type: 'default',
                  size: 'normal',
                  icon: '',
                  block: false,
                  plain: false,
                  square: false,
                  round: false,
                  disabled: false,
                  hairline: false,
                  url: '',
                },
                styles: {
                  display: 'inline-block',
                  zIndex: 1,
                },
                slots: {},
                actions: { click: [] },
                editor: { visibility: true },
              },
            ],
            'col-1': [
              {
                type: 'block',
                label: 'vant-button_2',
                widget: {
                  id: 'vant-button',
                  version: '1.0.0',
                  js: '',
                  css: '',
                },
                bid: 'com_ebdlwcjmag',
                props: {
                  text: '按钮',
                  type: 'default',
                  size: 'normal',
                  icon: '',
                  block: false,
                  plain: false,
                  square: false,
                  round: false,
                  disabled: false,
                  hairline: false,
                  url: '',
                },
                styles: {
                  display: 'inline-block',
                  zIndex: 1,
                },
                slots: {},
                actions: { click: [] },
                editor: { visibility: true },
              },
            ],
          },
          actions: {},
          editor: { visibility: true },
        },
        {
          type: 'block',
          label: 'vant-cell_1',
          widget: { id: 'vant-cell', version: '1.0.0', js: '', css: '' },
          bid: 'com_kyxjcofcxc',
          props: {
            'title': '标题',
            'value': '副标题',
            'label': '描述信息',
            'size': 'normal',
            'url': '',
            'clickable': false,
            'is-link': false,
            'arrow-direction': 'right',
            'center': false,
          },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
      ],
    },
    {
      title: '哈哈哈',
      path: '/detail',
      isHome: false,
      config: {},
      blocks: [
        {
          type: 'block',
          label: 'vant-cell_2',
          widget: { id: 'vant-cell', version: '1.0.0', js: '', css: '' },
          bid: 'com_isbloiuorj',
          props: {
            'title': '标题',
            'value': '副标题',
            'label': '描述信息',
            'size': 'normal',
            'url': '',
            'clickable': false,
            'is-link': false,
            'arrow-direction': 'right',
            'center': false,
          },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
        {
          type: 'block',
          label: 'vant-cell_3',
          widget: { id: 'vant-cell', version: '1.0.0', js: '', css: '' },
          bid: 'com_ntbxjfkzzo',
          props: {
            'title': '标题',
            'value': '副标题',
            'label': '描述信息',
            'size': 'normal',
            'url': '',
            'clickable': false,
            'is-link': false,
            'arrow-direction': 'right',
            'center': false,
          },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
        {
          type: 'block',
          label: 'vant-cell_4',
          widget: { id: 'vant-cell', version: '1.0.0', js: '', css: '' },
          bid: 'com_lyfnungcgs',
          props: {
            'title': '标题',
            'value': '副标题',
            'label': '描述信息',
            'size': 'normal',
            'url': '',
            'clickable': false,
            'is-link': false,
            'arrow-direction': 'right',
            'center': false,
          },
          styles: {
            display: 'block',
            zIndex: 1,
          },
          slots: {},
          actions: { click: [] },
          editor: { visibility: true },
        },
      ],
    },
  ],
}
