// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import 'vue'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsConfig: typeof import('./src/components/RightController/ActionsConfig.vue')['default']
    AppConfig: typeof import('./src/components/RightController/AppConfig.vue')['default']
    AttrsConfig: typeof import('./src/components/RightController/AttrsConfig.vue')['default']
    BasisComponent: typeof import('./src/components/LeftSidebar/BasisComponent.vue')['default']
    BusinessComponent: typeof import('./src/components/LeftSidebar/BusinessComponent.vue')['default']
    ContainerComponent: typeof import('./src/components/LeftSidebar/ContainerComponent.vue')['default']
    DataModel: typeof import('./src/components/LeftSidebar/DataModel.vue')['default']
    DraggableGroup: typeof import('./src/components/DraggableGroup.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    LeftSidebar: typeof import('./src/components/LeftSidebar/index.vue')['default']
    ModuleComponent: typeof import('./src/components/LeftSidebar/ModuleComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    PageConfig: typeof import('./src/components/RightController/PageConfig.vue')['default']
    PageTree: typeof import('./src/components/LeftSidebar/PageTree.vue')['default']
    RightController: typeof import('./src/components/RightController/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteBrand: typeof import('./src/components/Navbar/SiteBrand.vue')['default']
    StylesConfig: typeof import('./src/components/RightController/StylesConfig.vue')['default']
  }
}

export {}
