import { stylesDisplay, stylesPosition } from '@editor/common'
import type { WidgetProps } from '@spearjs/shared'

export default [
  {
    type: 'select',
    key: 'display',
    label: '布局模式',
    defaultValue: 'block',
    options: stylesDisplay,
    tips: '布局模式中关系到元素是否独占一行。如果选择block, 则元素独占一行；如果选择inline-block，则元素占据一行的部分空间。',
  },
  {
    type: 'select',
    key: 'position',
    label: '定位模式',
    defaultValue: '',
    options: stylesPosition,
    tips: '当元素的定位模式被设置为默认值或相对定位时，其本身还在流中，占据着固定的空间，同时相对于元素自身进行定位偏移；如果设置为绝对定位，则脱离了本身所在的流，不占据原来的空间，相对与其所在父级容器进行定位偏移；如果设置为窗体定位，则脱离了本身所在的流，不占据原来的空间，并且相对于窗体进行定位偏移；如果设置为粘性定位，其本身不在流中，并且占据原来的空间，当元素距离窗体达到预设值，则会相对于窗体固定。',
  },
  {
    type: 'number',
    key: 'zIndex',
    label: '叠层顺序',
    defaultValue: 0,
    step: 1,
    tips: '叠层顺序控制元素相对于其他顺序的叠放顺序，当两个同级元素叠放在一起时，叠层顺序数值高的，位于上层。',
  },
  {
    type: 'slider',
    key: 'opacity',
    label: '透明度',
    defaultValue: 1,
    step: 0.01,
    max: 1,
    min: 0,
    showInput: true,
    tips: '设置元素的透明度',
  },
  {
    type: 'color',
    key: 'backgroundColor',
    label: '背景色',
    showAlpha: true,
    colorFormat: 'rgb',
    predefine: ['rgba(255,255,255,1)', 'rgba(240, 240, 240, 1)'],
  },
  {
    type: 'group',
    label: '边框设置',
    spread: false,
    tips: '控制边框的样式',
    props: [
      {
        type: 'border',
        key: 'border',
        label: '边框',
        showAlpha: true,
        colorFormat: 'rgb',
      },
      {
        type: 'border',
        key: 'borderTop',
        label: '上边框',
        showAlpha: true,
        colorFormat: 'rgb',
      },
      {
        type: 'border',
        key: 'borderRight',
        label: '右边框',
        showAlpha: true,
        colorFormat: 'rgb',
      },
      {
        type: 'border',
        key: 'borderBottom',
        label: '下边框',
        showAlpha: true,
        colorFormat: 'rgb',
      },
      {
        type: 'border',
        key: 'borderLeft',
        label: '左边框',
        showAlpha: true,
        colorFormat: 'rgb',
      },
    ],
  },
] as WidgetProps
